/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedadminIndexRouteImport } from './routes/_authenticated/(admin)/index'
import { Route as AuthenticatedmasterMasterRouteImport } from './routes/_authenticated/(master)/master'
import { Route as AuthenticatedadminRegisterRouteImport } from './routes/_authenticated/(admin)/register'
import { Route as AuthenticatedadminCreateCategoryRouteImport } from './routes/_authenticated/(admin)/create-category'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedadminIndexRoute = AuthenticatedadminIndexRouteImport.update({
  id: '/(admin)/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedmasterMasterRoute =
  AuthenticatedmasterMasterRouteImport.update({
    id: '/(master)/master',
    path: '/master',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminRegisterRoute =
  AuthenticatedadminRegisterRouteImport.update({
    id: '/(admin)/register',
    path: '/register',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminCreateCategoryRoute =
  AuthenticatedadminCreateCategoryRouteImport.update({
    id: '/(admin)/create-category',
    path: '/create-category',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof authLoginRoute
  '/create-category': typeof AuthenticatedadminCreateCategoryRoute
  '/register': typeof AuthenticatedadminRegisterRoute
  '/master': typeof AuthenticatedmasterMasterRoute
  '/': typeof AuthenticatedadminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/create-category': typeof AuthenticatedadminCreateCategoryRoute
  '/register': typeof AuthenticatedadminRegisterRoute
  '/master': typeof AuthenticatedmasterMasterRoute
  '/': typeof AuthenticatedadminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/(admin)/create-category': typeof AuthenticatedadminCreateCategoryRoute
  '/_authenticated/(admin)/register': typeof AuthenticatedadminRegisterRoute
  '/_authenticated/(master)/master': typeof AuthenticatedmasterMasterRoute
  '/_authenticated/(admin)/': typeof AuthenticatedadminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/login' | '/create-category' | '/register' | '/master' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/create-category' | '/register' | '/master' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/login'
    | '/_authenticated/(admin)/create-category'
    | '/_authenticated/(admin)/register'
    | '/_authenticated/(master)/master'
    | '/_authenticated/(admin)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/(admin)/create-category': {
      id: '/_authenticated/(admin)/create-category'
      path: '/create-category'
      fullPath: '/create-category'
      preLoaderRoute: typeof AuthenticatedadminCreateCategoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/register': {
      id: '/_authenticated/(admin)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticatedadminRegisterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(master)/master': {
      id: '/_authenticated/(master)/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedmasterMasterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/': {
      id: '/_authenticated/(admin)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedadminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

declare module './routes/_authenticated' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated',
    FileRoutesByPath['/_authenticated']['parentRoute'],
    FileRoutesByPath['/_authenticated']['id'],
    FileRoutesByPath['/_authenticated']['path'],
    FileRoutesByPath['/_authenticated']['fullPath']
  >
}
declare module './routes/(auth)/login' {
  const createFileRoute: CreateFileRoute<
    '/(auth)/login',
    FileRoutesByPath['/(auth)/login']['parentRoute'],
    FileRoutesByPath['/(auth)/login']['id'],
    FileRoutesByPath['/(auth)/login']['path'],
    FileRoutesByPath['/(auth)/login']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/create-category' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/create-category',
    FileRoutesByPath['/_authenticated/(admin)/create-category']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/create-category']['id'],
    FileRoutesByPath['/_authenticated/(admin)/create-category']['path'],
    FileRoutesByPath['/_authenticated/(admin)/create-category']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/register' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/register',
    FileRoutesByPath['/_authenticated/(admin)/register']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/register']['id'],
    FileRoutesByPath['/_authenticated/(admin)/register']['path'],
    FileRoutesByPath['/_authenticated/(admin)/register']['fullPath']
  >
}
declare module './routes/_authenticated/(master)/master' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(master)/master',
    FileRoutesByPath['/_authenticated/(master)/master']['parentRoute'],
    FileRoutesByPath['/_authenticated/(master)/master']['id'],
    FileRoutesByPath['/_authenticated/(master)/master']['path'],
    FileRoutesByPath['/_authenticated/(master)/master']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/',
    FileRoutesByPath['/_authenticated/(admin)/']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/']['id'],
    FileRoutesByPath['/_authenticated/(admin)/']['path'],
    FileRoutesByPath['/_authenticated/(admin)/']['fullPath']
  >
}

interface AuthenticatedRouteChildren {
  AuthenticatedadminCreateCategoryRoute: typeof AuthenticatedadminCreateCategoryRoute
  AuthenticatedadminRegisterRoute: typeof AuthenticatedadminRegisterRoute
  AuthenticatedmasterMasterRoute: typeof AuthenticatedmasterMasterRoute
  AuthenticatedadminIndexRoute: typeof AuthenticatedadminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedadminCreateCategoryRoute: AuthenticatedadminCreateCategoryRoute,
  AuthenticatedadminRegisterRoute: AuthenticatedadminRegisterRoute,
  AuthenticatedmasterMasterRoute: AuthenticatedmasterMasterRoute,
  AuthenticatedadminIndexRoute: AuthenticatedadminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
