/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedMasterIndexRouteImport } from './routes/_authenticated/master/index'
import { Route as AuthenticatedadminIndexRouteImport } from './routes/_authenticated/(admin)/index'
import { Route as AuthenticatedMasterUnlockedCitiesRouteImport } from './routes/_authenticated/master/unlocked-cities'
import { Route as AuthenticatedMasterUnlockCityRouteImport } from './routes/_authenticated/master/unlock-city'
import { Route as AuthenticatedMasterSettingsRouteImport } from './routes/_authenticated/master/settings'
import { Route as AuthenticatedMasterNotificationsRouteImport } from './routes/_authenticated/master/notifications'
import { Route as AuthenticatedMasterMasterProfileRouteImport } from './routes/_authenticated/master/master-profile'
import { Route as AuthenticatedMasterJobAssignmentRouteImport } from './routes/_authenticated/master/job-assignment'
import { Route as AuthenticatedadminRegisterRouteImport } from './routes/_authenticated/(admin)/register'
import { Route as AuthenticatedadminCreateCityRouteImport } from './routes/_authenticated/(admin)/create-city'
import { Route as AuthenticatedadminCreateCategoryRouteImport } from './routes/_authenticated/(admin)/create-category'
import { Route as AuthenticatedMasterReviewsRouteRouteImport } from './routes/_authenticated/master/reviews/route'
import { Route as AuthenticatedadminBillingRouteRouteImport } from './routes/_authenticated/(admin)/billing/route'
import { Route as AuthenticatedMasterReviewsIndexRouteImport } from './routes/_authenticated/master/reviews/index'
import { Route as AuthenticatedMasterLeadsIndexRouteImport } from './routes/_authenticated/master/leads/index'
import { Route as AuthenticatedadminReviewsIndexRouteImport } from './routes/_authenticated/(admin)/reviews/index'
import { Route as AuthenticatedadminBillingIndexRouteImport } from './routes/_authenticated/(admin)/billing/index'
import { Route as AuthenticatedMasterLeadsIdRouteImport } from './routes/_authenticated/master/leads/$id'
import { Route as AuthenticatedadminGetMastersAllMastersRouteImport } from './routes/_authenticated/(admin)/get-masters/all-masters'
import { Route as AuthenticatedadminGetMastersIdRouteImport } from './routes/_authenticated/(admin)/get-masters/$id'
import { Route as AuthenticatedadminCreateJobsJobsRouteImport } from './routes/_authenticated/(admin)/create-jobs/jobs'
import { Route as AuthenticatedadminCreateJobsIdRouteImport } from './routes/_authenticated/(admin)/create-jobs/$id'
import { Route as AuthenticatedadminBillingTriggerRouteImport } from './routes/_authenticated/(admin)/billing/trigger'
import { Route as AuthenticatedadminBillingStatsRouteImport } from './routes/_authenticated/(admin)/billing/stats'
import { Route as AuthenticatedadminBillingHistoryRouteImport } from './routes/_authenticated/(admin)/billing/history'
import { Route as AuthenticatedadminGetMastersLeadsLeadsIdRouteImport } from './routes/_authenticated/(admin)/get-masters/leads/$leadsId'

const AuthenticatedMasterReviewsStatsLazyRouteImport = createFileRoute(
  '/_authenticated/master/reviews/stats',
)()

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMasterIndexRoute =
  AuthenticatedMasterIndexRouteImport.update({
    id: '/master/',
    path: '/master/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminIndexRoute = AuthenticatedadminIndexRouteImport.update({
  id: '/(admin)/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMasterUnlockedCitiesRoute =
  AuthenticatedMasterUnlockedCitiesRouteImport.update({
    id: '/master/unlocked-cities',
    path: '/master/unlocked-cities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterUnlockCityRoute =
  AuthenticatedMasterUnlockCityRouteImport.update({
    id: '/master/unlock-city',
    path: '/master/unlock-city',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterSettingsRoute =
  AuthenticatedMasterSettingsRouteImport.update({
    id: '/master/settings',
    path: '/master/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterNotificationsRoute =
  AuthenticatedMasterNotificationsRouteImport.update({
    id: '/master/notifications',
    path: '/master/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterMasterProfileRoute =
  AuthenticatedMasterMasterProfileRouteImport.update({
    id: '/master/master-profile',
    path: '/master/master-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterJobAssignmentRoute =
  AuthenticatedMasterJobAssignmentRouteImport.update({
    id: '/master/job-assignment',
    path: '/master/job-assignment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminRegisterRoute =
  AuthenticatedadminRegisterRouteImport.update({
    id: '/(admin)/register',
    path: '/register',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminCreateCityRoute =
  AuthenticatedadminCreateCityRouteImport.update({
    id: '/(admin)/create-city',
    path: '/create-city',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminCreateCategoryRoute =
  AuthenticatedadminCreateCategoryRouteImport.update({
    id: '/(admin)/create-category',
    path: '/create-category',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterReviewsRouteRoute =
  AuthenticatedMasterReviewsRouteRouteImport.update({
    id: '/master/reviews',
    path: '/master/reviews',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminBillingRouteRoute =
  AuthenticatedadminBillingRouteRouteImport.update({
    id: '/(admin)/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterReviewsIndexRoute =
  AuthenticatedMasterReviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMasterReviewsRouteRoute,
  } as any)
const AuthenticatedMasterLeadsIndexRoute =
  AuthenticatedMasterLeadsIndexRouteImport.update({
    id: '/master/leads/',
    path: '/master/leads/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminReviewsIndexRoute =
  AuthenticatedadminReviewsIndexRouteImport.update({
    id: '/(admin)/reviews/',
    path: '/reviews/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminBillingIndexRoute =
  AuthenticatedadminBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedadminBillingRouteRoute,
  } as any)
const AuthenticatedMasterReviewsStatsLazyRoute =
  AuthenticatedMasterReviewsStatsLazyRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedMasterReviewsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/master/reviews/stats.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedMasterLeadsIdRoute =
  AuthenticatedMasterLeadsIdRouteImport.update({
    id: '/master/leads/$id',
    path: '/master/leads/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminGetMastersAllMastersRoute =
  AuthenticatedadminGetMastersAllMastersRouteImport.update({
    id: '/(admin)/get-masters/all-masters',
    path: '/get-masters/all-masters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminGetMastersIdRoute =
  AuthenticatedadminGetMastersIdRouteImport.update({
    id: '/(admin)/get-masters/$id',
    path: '/get-masters/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminCreateJobsJobsRoute =
  AuthenticatedadminCreateJobsJobsRouteImport.update({
    id: '/(admin)/create-jobs/jobs',
    path: '/create-jobs/jobs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminCreateJobsIdRoute =
  AuthenticatedadminCreateJobsIdRouteImport.update({
    id: '/(admin)/create-jobs/$id',
    path: '/create-jobs/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminBillingTriggerRoute =
  AuthenticatedadminBillingTriggerRouteImport.update({
    id: '/trigger',
    path: '/trigger',
    getParentRoute: () => AuthenticatedadminBillingRouteRoute,
  } as any)
const AuthenticatedadminBillingStatsRoute =
  AuthenticatedadminBillingStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedadminBillingRouteRoute,
  } as any)
const AuthenticatedadminBillingHistoryRoute =
  AuthenticatedadminBillingHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedadminBillingRouteRoute,
  } as any)
const AuthenticatedadminGetMastersLeadsLeadsIdRoute =
  AuthenticatedadminGetMastersLeadsLeadsIdRouteImport.update({
    id: '/(admin)/get-masters/leads/$leadsId',
    path: '/get-masters/leads/$leadsId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof authLoginRoute
  '/billing': typeof AuthenticatedadminBillingRouteRouteWithChildren
  '/master/reviews': typeof AuthenticatedMasterReviewsRouteRouteWithChildren
  '/create-category': typeof AuthenticatedadminCreateCategoryRoute
  '/create-city': typeof AuthenticatedadminCreateCityRoute
  '/register': typeof AuthenticatedadminRegisterRoute
  '/master/job-assignment': typeof AuthenticatedMasterJobAssignmentRoute
  '/master/master-profile': typeof AuthenticatedMasterMasterProfileRoute
  '/master/notifications': typeof AuthenticatedMasterNotificationsRoute
  '/master/settings': typeof AuthenticatedMasterSettingsRoute
  '/master/unlock-city': typeof AuthenticatedMasterUnlockCityRoute
  '/master/unlocked-cities': typeof AuthenticatedMasterUnlockedCitiesRoute
  '/': typeof AuthenticatedadminIndexRoute
  '/master': typeof AuthenticatedMasterIndexRoute
  '/billing/history': typeof AuthenticatedadminBillingHistoryRoute
  '/billing/stats': typeof AuthenticatedadminBillingStatsRoute
  '/billing/trigger': typeof AuthenticatedadminBillingTriggerRoute
  '/create-jobs/$id': typeof AuthenticatedadminCreateJobsIdRoute
  '/create-jobs/jobs': typeof AuthenticatedadminCreateJobsJobsRoute
  '/get-masters/$id': typeof AuthenticatedadminGetMastersIdRoute
  '/get-masters/all-masters': typeof AuthenticatedadminGetMastersAllMastersRoute
  '/master/leads/$id': typeof AuthenticatedMasterLeadsIdRoute
  '/master/reviews/stats': typeof AuthenticatedMasterReviewsStatsLazyRoute
  '/billing/': typeof AuthenticatedadminBillingIndexRoute
  '/reviews': typeof AuthenticatedadminReviewsIndexRoute
  '/master/leads': typeof AuthenticatedMasterLeadsIndexRoute
  '/master/reviews/': typeof AuthenticatedMasterReviewsIndexRoute
  '/get-masters/leads/$leadsId': typeof AuthenticatedadminGetMastersLeadsLeadsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/create-category': typeof AuthenticatedadminCreateCategoryRoute
  '/create-city': typeof AuthenticatedadminCreateCityRoute
  '/register': typeof AuthenticatedadminRegisterRoute
  '/master/job-assignment': typeof AuthenticatedMasterJobAssignmentRoute
  '/master/master-profile': typeof AuthenticatedMasterMasterProfileRoute
  '/master/notifications': typeof AuthenticatedMasterNotificationsRoute
  '/master/settings': typeof AuthenticatedMasterSettingsRoute
  '/master/unlock-city': typeof AuthenticatedMasterUnlockCityRoute
  '/master/unlocked-cities': typeof AuthenticatedMasterUnlockedCitiesRoute
  '/': typeof AuthenticatedadminIndexRoute
  '/master': typeof AuthenticatedMasterIndexRoute
  '/billing/history': typeof AuthenticatedadminBillingHistoryRoute
  '/billing/stats': typeof AuthenticatedadminBillingStatsRoute
  '/billing/trigger': typeof AuthenticatedadminBillingTriggerRoute
  '/create-jobs/$id': typeof AuthenticatedadminCreateJobsIdRoute
  '/create-jobs/jobs': typeof AuthenticatedadminCreateJobsJobsRoute
  '/get-masters/$id': typeof AuthenticatedadminGetMastersIdRoute
  '/get-masters/all-masters': typeof AuthenticatedadminGetMastersAllMastersRoute
  '/master/leads/$id': typeof AuthenticatedMasterLeadsIdRoute
  '/master/reviews/stats': typeof AuthenticatedMasterReviewsStatsLazyRoute
  '/billing': typeof AuthenticatedadminBillingIndexRoute
  '/reviews': typeof AuthenticatedadminReviewsIndexRoute
  '/master/leads': typeof AuthenticatedMasterLeadsIndexRoute
  '/master/reviews': typeof AuthenticatedMasterReviewsIndexRoute
  '/get-masters/leads/$leadsId': typeof AuthenticatedadminGetMastersLeadsLeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/(admin)/billing': typeof AuthenticatedadminBillingRouteRouteWithChildren
  '/_authenticated/master/reviews': typeof AuthenticatedMasterReviewsRouteRouteWithChildren
  '/_authenticated/(admin)/create-category': typeof AuthenticatedadminCreateCategoryRoute
  '/_authenticated/(admin)/create-city': typeof AuthenticatedadminCreateCityRoute
  '/_authenticated/(admin)/register': typeof AuthenticatedadminRegisterRoute
  '/_authenticated/master/job-assignment': typeof AuthenticatedMasterJobAssignmentRoute
  '/_authenticated/master/master-profile': typeof AuthenticatedMasterMasterProfileRoute
  '/_authenticated/master/notifications': typeof AuthenticatedMasterNotificationsRoute
  '/_authenticated/master/settings': typeof AuthenticatedMasterSettingsRoute
  '/_authenticated/master/unlock-city': typeof AuthenticatedMasterUnlockCityRoute
  '/_authenticated/master/unlocked-cities': typeof AuthenticatedMasterUnlockedCitiesRoute
  '/_authenticated/(admin)/': typeof AuthenticatedadminIndexRoute
  '/_authenticated/master/': typeof AuthenticatedMasterIndexRoute
  '/_authenticated/(admin)/billing/history': typeof AuthenticatedadminBillingHistoryRoute
  '/_authenticated/(admin)/billing/stats': typeof AuthenticatedadminBillingStatsRoute
  '/_authenticated/(admin)/billing/trigger': typeof AuthenticatedadminBillingTriggerRoute
  '/_authenticated/(admin)/create-jobs/$id': typeof AuthenticatedadminCreateJobsIdRoute
  '/_authenticated/(admin)/create-jobs/jobs': typeof AuthenticatedadminCreateJobsJobsRoute
  '/_authenticated/(admin)/get-masters/$id': typeof AuthenticatedadminGetMastersIdRoute
  '/_authenticated/(admin)/get-masters/all-masters': typeof AuthenticatedadminGetMastersAllMastersRoute
  '/_authenticated/master/leads/$id': typeof AuthenticatedMasterLeadsIdRoute
  '/_authenticated/master/reviews/stats': typeof AuthenticatedMasterReviewsStatsLazyRoute
  '/_authenticated/(admin)/billing/': typeof AuthenticatedadminBillingIndexRoute
  '/_authenticated/(admin)/reviews/': typeof AuthenticatedadminReviewsIndexRoute
  '/_authenticated/master/leads/': typeof AuthenticatedMasterLeadsIndexRoute
  '/_authenticated/master/reviews/': typeof AuthenticatedMasterReviewsIndexRoute
  '/_authenticated/(admin)/get-masters/leads/$leadsId': typeof AuthenticatedadminGetMastersLeadsLeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/billing'
    | '/master/reviews'
    | '/create-category'
    | '/create-city'
    | '/register'
    | '/master/job-assignment'
    | '/master/master-profile'
    | '/master/notifications'
    | '/master/settings'
    | '/master/unlock-city'
    | '/master/unlocked-cities'
    | '/'
    | '/master'
    | '/billing/history'
    | '/billing/stats'
    | '/billing/trigger'
    | '/create-jobs/$id'
    | '/create-jobs/jobs'
    | '/get-masters/$id'
    | '/get-masters/all-masters'
    | '/master/leads/$id'
    | '/master/reviews/stats'
    | '/billing/'
    | '/reviews'
    | '/master/leads'
    | '/master/reviews/'
    | '/get-masters/leads/$leadsId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/create-category'
    | '/create-city'
    | '/register'
    | '/master/job-assignment'
    | '/master/master-profile'
    | '/master/notifications'
    | '/master/settings'
    | '/master/unlock-city'
    | '/master/unlocked-cities'
    | '/'
    | '/master'
    | '/billing/history'
    | '/billing/stats'
    | '/billing/trigger'
    | '/create-jobs/$id'
    | '/create-jobs/jobs'
    | '/get-masters/$id'
    | '/get-masters/all-masters'
    | '/master/leads/$id'
    | '/master/reviews/stats'
    | '/billing'
    | '/reviews'
    | '/master/leads'
    | '/master/reviews'
    | '/get-masters/leads/$leadsId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/login'
    | '/_authenticated/(admin)/billing'
    | '/_authenticated/master/reviews'
    | '/_authenticated/(admin)/create-category'
    | '/_authenticated/(admin)/create-city'
    | '/_authenticated/(admin)/register'
    | '/_authenticated/master/job-assignment'
    | '/_authenticated/master/master-profile'
    | '/_authenticated/master/notifications'
    | '/_authenticated/master/settings'
    | '/_authenticated/master/unlock-city'
    | '/_authenticated/master/unlocked-cities'
    | '/_authenticated/(admin)/'
    | '/_authenticated/master/'
    | '/_authenticated/(admin)/billing/history'
    | '/_authenticated/(admin)/billing/stats'
    | '/_authenticated/(admin)/billing/trigger'
    | '/_authenticated/(admin)/create-jobs/$id'
    | '/_authenticated/(admin)/create-jobs/jobs'
    | '/_authenticated/(admin)/get-masters/$id'
    | '/_authenticated/(admin)/get-masters/all-masters'
    | '/_authenticated/master/leads/$id'
    | '/_authenticated/master/reviews/stats'
    | '/_authenticated/(admin)/billing/'
    | '/_authenticated/(admin)/reviews/'
    | '/_authenticated/master/leads/'
    | '/_authenticated/master/reviews/'
    | '/_authenticated/(admin)/get-masters/leads/$leadsId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/(admin)/billing': {
      id: '/_authenticated/(admin)/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedadminBillingRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/reviews': {
      id: '/_authenticated/master/reviews'
      path: '/master/reviews'
      fullPath: '/master/reviews'
      preLoaderRoute: typeof AuthenticatedMasterReviewsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/create-category': {
      id: '/_authenticated/(admin)/create-category'
      path: '/create-category'
      fullPath: '/create-category'
      preLoaderRoute: typeof AuthenticatedadminCreateCategoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/create-city': {
      id: '/_authenticated/(admin)/create-city'
      path: '/create-city'
      fullPath: '/create-city'
      preLoaderRoute: typeof AuthenticatedadminCreateCityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/register': {
      id: '/_authenticated/(admin)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticatedadminRegisterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/job-assignment': {
      id: '/_authenticated/master/job-assignment'
      path: '/master/job-assignment'
      fullPath: '/master/job-assignment'
      preLoaderRoute: typeof AuthenticatedMasterJobAssignmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/master-profile': {
      id: '/_authenticated/master/master-profile'
      path: '/master/master-profile'
      fullPath: '/master/master-profile'
      preLoaderRoute: typeof AuthenticatedMasterMasterProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/notifications': {
      id: '/_authenticated/master/notifications'
      path: '/master/notifications'
      fullPath: '/master/notifications'
      preLoaderRoute: typeof AuthenticatedMasterNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/settings': {
      id: '/_authenticated/master/settings'
      path: '/master/settings'
      fullPath: '/master/settings'
      preLoaderRoute: typeof AuthenticatedMasterSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/unlock-city': {
      id: '/_authenticated/master/unlock-city'
      path: '/master/unlock-city'
      fullPath: '/master/unlock-city'
      preLoaderRoute: typeof AuthenticatedMasterUnlockCityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/unlocked-cities': {
      id: '/_authenticated/master/unlocked-cities'
      path: '/master/unlocked-cities'
      fullPath: '/master/unlocked-cities'
      preLoaderRoute: typeof AuthenticatedMasterUnlockedCitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/': {
      id: '/_authenticated/(admin)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedadminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/': {
      id: '/_authenticated/master/'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/billing/history': {
      id: '/_authenticated/(admin)/billing/history'
      path: '/history'
      fullPath: '/billing/history'
      preLoaderRoute: typeof AuthenticatedadminBillingHistoryRouteImport
      parentRoute: typeof AuthenticatedadminBillingRouteRoute
    }
    '/_authenticated/(admin)/billing/stats': {
      id: '/_authenticated/(admin)/billing/stats'
      path: '/stats'
      fullPath: '/billing/stats'
      preLoaderRoute: typeof AuthenticatedadminBillingStatsRouteImport
      parentRoute: typeof AuthenticatedadminBillingRouteRoute
    }
    '/_authenticated/(admin)/billing/trigger': {
      id: '/_authenticated/(admin)/billing/trigger'
      path: '/trigger'
      fullPath: '/billing/trigger'
      preLoaderRoute: typeof AuthenticatedadminBillingTriggerRouteImport
      parentRoute: typeof AuthenticatedadminBillingRouteRoute
    }
    '/_authenticated/(admin)/create-jobs/$id': {
      id: '/_authenticated/(admin)/create-jobs/$id'
      path: '/create-jobs/$id'
      fullPath: '/create-jobs/$id'
      preLoaderRoute: typeof AuthenticatedadminCreateJobsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/create-jobs/jobs': {
      id: '/_authenticated/(admin)/create-jobs/jobs'
      path: '/create-jobs/jobs'
      fullPath: '/create-jobs/jobs'
      preLoaderRoute: typeof AuthenticatedadminCreateJobsJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/get-masters/$id': {
      id: '/_authenticated/(admin)/get-masters/$id'
      path: '/get-masters/$id'
      fullPath: '/get-masters/$id'
      preLoaderRoute: typeof AuthenticatedadminGetMastersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/get-masters/all-masters': {
      id: '/_authenticated/(admin)/get-masters/all-masters'
      path: '/get-masters/all-masters'
      fullPath: '/get-masters/all-masters'
      preLoaderRoute: typeof AuthenticatedadminGetMastersAllMastersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/leads/$id': {
      id: '/_authenticated/master/leads/$id'
      path: '/master/leads/$id'
      fullPath: '/master/leads/$id'
      preLoaderRoute: typeof AuthenticatedMasterLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/reviews/stats': {
      id: '/_authenticated/master/reviews/stats'
      path: '/stats'
      fullPath: '/master/reviews/stats'
      preLoaderRoute: typeof AuthenticatedMasterReviewsStatsLazyRouteImport
      parentRoute: typeof AuthenticatedMasterReviewsRouteRoute
    }
    '/_authenticated/(admin)/billing/': {
      id: '/_authenticated/(admin)/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthenticatedadminBillingIndexRouteImport
      parentRoute: typeof AuthenticatedadminBillingRouteRoute
    }
    '/_authenticated/(admin)/reviews/': {
      id: '/_authenticated/(admin)/reviews/'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedadminReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/leads/': {
      id: '/_authenticated/master/leads/'
      path: '/master/leads'
      fullPath: '/master/leads'
      preLoaderRoute: typeof AuthenticatedMasterLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/reviews/': {
      id: '/_authenticated/master/reviews/'
      path: '/'
      fullPath: '/master/reviews/'
      preLoaderRoute: typeof AuthenticatedMasterReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedMasterReviewsRouteRoute
    }
    '/_authenticated/(admin)/get-masters/leads/$leadsId': {
      id: '/_authenticated/(admin)/get-masters/leads/$leadsId'
      path: '/get-masters/leads/$leadsId'
      fullPath: '/get-masters/leads/$leadsId'
      preLoaderRoute: typeof AuthenticatedadminGetMastersLeadsLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/reviews/stats': {
      id: '/_authenticated/master/reviews/stats'
      path: '/stats'
      fullPath: '/master/reviews/stats'
      preLoaderRoute: typeof AuthenticatedMasterReviewsStatsLazyRouteImport
      parentRoute: typeof AuthenticatedMasterReviewsRouteRoute
    }
  }
}

declare module './routes/_authenticated' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated',
    FileRoutesByPath['/_authenticated']['parentRoute'],
    FileRoutesByPath['/_authenticated']['id'],
    FileRoutesByPath['/_authenticated']['path'],
    FileRoutesByPath['/_authenticated']['fullPath']
  >
}
declare module './routes/(auth)/login' {
  const createFileRoute: CreateFileRoute<
    '/(auth)/login',
    FileRoutesByPath['/(auth)/login']['parentRoute'],
    FileRoutesByPath['/(auth)/login']['id'],
    FileRoutesByPath['/(auth)/login']['path'],
    FileRoutesByPath['/(auth)/login']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/billing/route' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/billing',
    FileRoutesByPath['/_authenticated/(admin)/billing']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/billing']['id'],
    FileRoutesByPath['/_authenticated/(admin)/billing']['path'],
    FileRoutesByPath['/_authenticated/(admin)/billing']['fullPath']
  >
}
declare module './routes/_authenticated/master/reviews/route' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/master/reviews',
    FileRoutesByPath['/_authenticated/master/reviews']['parentRoute'],
    FileRoutesByPath['/_authenticated/master/reviews']['id'],
    FileRoutesByPath['/_authenticated/master/reviews']['path'],
    FileRoutesByPath['/_authenticated/master/reviews']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/create-category' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/create-category',
    FileRoutesByPath['/_authenticated/(admin)/create-category']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/create-category']['id'],
    FileRoutesByPath['/_authenticated/(admin)/create-category']['path'],
    FileRoutesByPath['/_authenticated/(admin)/create-category']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/create-city' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/create-city',
    FileRoutesByPath['/_authenticated/(admin)/create-city']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/create-city']['id'],
    FileRoutesByPath['/_authenticated/(admin)/create-city']['path'],
    FileRoutesByPath['/_authenticated/(admin)/create-city']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/register' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/register',
    FileRoutesByPath['/_authenticated/(admin)/register']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/register']['id'],
    FileRoutesByPath['/_authenticated/(admin)/register']['path'],
    FileRoutesByPath['/_authenticated/(admin)/register']['fullPath']
  >
}
declare module './routes/_authenticated/master/job-assignment' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/master/job-assignment',
    FileRoutesByPath['/_authenticated/master/job-assignment']['parentRoute'],
    FileRoutesByPath['/_authenticated/master/job-assignment']['id'],
    FileRoutesByPath['/_authenticated/master/job-assignment']['path'],
    FileRoutesByPath['/_authenticated/master/job-assignment']['fullPath']
  >
}
declare module './routes/_authenticated/master/master-profile' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/master/master-profile',
    FileRoutesByPath['/_authenticated/master/master-profile']['parentRoute'],
    FileRoutesByPath['/_authenticated/master/master-profile']['id'],
    FileRoutesByPath['/_authenticated/master/master-profile']['path'],
    FileRoutesByPath['/_authenticated/master/master-profile']['fullPath']
  >
}
declare module './routes/_authenticated/master/notifications' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/master/notifications',
    FileRoutesByPath['/_authenticated/master/notifications']['parentRoute'],
    FileRoutesByPath['/_authenticated/master/notifications']['id'],
    FileRoutesByPath['/_authenticated/master/notifications']['path'],
    FileRoutesByPath['/_authenticated/master/notifications']['fullPath']
  >
}
declare module './routes/_authenticated/master/settings' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/master/settings',
    FileRoutesByPath['/_authenticated/master/settings']['parentRoute'],
    FileRoutesByPath['/_authenticated/master/settings']['id'],
    FileRoutesByPath['/_authenticated/master/settings']['path'],
    FileRoutesByPath['/_authenticated/master/settings']['fullPath']
  >
}
declare module './routes/_authenticated/master/unlock-city' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/master/unlock-city',
    FileRoutesByPath['/_authenticated/master/unlock-city']['parentRoute'],
    FileRoutesByPath['/_authenticated/master/unlock-city']['id'],
    FileRoutesByPath['/_authenticated/master/unlock-city']['path'],
    FileRoutesByPath['/_authenticated/master/unlock-city']['fullPath']
  >
}
declare module './routes/_authenticated/master/unlocked-cities' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/master/unlocked-cities',
    FileRoutesByPath['/_authenticated/master/unlocked-cities']['parentRoute'],
    FileRoutesByPath['/_authenticated/master/unlocked-cities']['id'],
    FileRoutesByPath['/_authenticated/master/unlocked-cities']['path'],
    FileRoutesByPath['/_authenticated/master/unlocked-cities']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/',
    FileRoutesByPath['/_authenticated/(admin)/']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/']['id'],
    FileRoutesByPath['/_authenticated/(admin)/']['path'],
    FileRoutesByPath['/_authenticated/(admin)/']['fullPath']
  >
}
declare module './routes/_authenticated/master/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/master/',
    FileRoutesByPath['/_authenticated/master/']['parentRoute'],
    FileRoutesByPath['/_authenticated/master/']['id'],
    FileRoutesByPath['/_authenticated/master/']['path'],
    FileRoutesByPath['/_authenticated/master/']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/billing/history' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/billing/history',
    FileRoutesByPath['/_authenticated/(admin)/billing/history']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/billing/history']['id'],
    FileRoutesByPath['/_authenticated/(admin)/billing/history']['path'],
    FileRoutesByPath['/_authenticated/(admin)/billing/history']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/billing/stats' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/billing/stats',
    FileRoutesByPath['/_authenticated/(admin)/billing/stats']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/billing/stats']['id'],
    FileRoutesByPath['/_authenticated/(admin)/billing/stats']['path'],
    FileRoutesByPath['/_authenticated/(admin)/billing/stats']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/billing/trigger' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/billing/trigger',
    FileRoutesByPath['/_authenticated/(admin)/billing/trigger']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/billing/trigger']['id'],
    FileRoutesByPath['/_authenticated/(admin)/billing/trigger']['path'],
    FileRoutesByPath['/_authenticated/(admin)/billing/trigger']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/create-jobs/$id' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/create-jobs/$id',
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/$id']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/$id']['id'],
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/$id']['path'],
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/$id']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/create-jobs/jobs' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/create-jobs/jobs',
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/jobs']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/jobs']['id'],
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/jobs']['path'],
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/jobs']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/get-masters/$id' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/get-masters/$id',
    FileRoutesByPath['/_authenticated/(admin)/get-masters/$id']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/get-masters/$id']['id'],
    FileRoutesByPath['/_authenticated/(admin)/get-masters/$id']['path'],
    FileRoutesByPath['/_authenticated/(admin)/get-masters/$id']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/get-masters/all-masters' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/get-masters/all-masters',
    FileRoutesByPath['/_authenticated/(admin)/get-masters/all-masters']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/get-masters/all-masters']['id'],
    FileRoutesByPath['/_authenticated/(admin)/get-masters/all-masters']['path'],
    FileRoutesByPath['/_authenticated/(admin)/get-masters/all-masters']['fullPath']
  >
}
declare module './routes/_authenticated/master/leads/$id' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/master/leads/$id',
    FileRoutesByPath['/_authenticated/master/leads/$id']['parentRoute'],
    FileRoutesByPath['/_authenticated/master/leads/$id']['id'],
    FileRoutesByPath['/_authenticated/master/leads/$id']['path'],
    FileRoutesByPath['/_authenticated/master/leads/$id']['fullPath']
  >
}
declare module './routes/_authenticated/master/reviews/stats.lazy' {
  const createLazyFileRoute: CreateLazyFileRoute<
    FileRoutesByPath['/_authenticated/master/reviews/stats']['preLoaderRoute']
  >
}
declare module './routes/_authenticated/(admin)/billing/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/billing/',
    FileRoutesByPath['/_authenticated/(admin)/billing/']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/billing/']['id'],
    FileRoutesByPath['/_authenticated/(admin)/billing/']['path'],
    FileRoutesByPath['/_authenticated/(admin)/billing/']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/reviews/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/reviews/',
    FileRoutesByPath['/_authenticated/(admin)/reviews/']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/reviews/']['id'],
    FileRoutesByPath['/_authenticated/(admin)/reviews/']['path'],
    FileRoutesByPath['/_authenticated/(admin)/reviews/']['fullPath']
  >
}
declare module './routes/_authenticated/master/leads/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/master/leads/',
    FileRoutesByPath['/_authenticated/master/leads/']['parentRoute'],
    FileRoutesByPath['/_authenticated/master/leads/']['id'],
    FileRoutesByPath['/_authenticated/master/leads/']['path'],
    FileRoutesByPath['/_authenticated/master/leads/']['fullPath']
  >
}
declare module './routes/_authenticated/master/reviews/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/master/reviews/',
    FileRoutesByPath['/_authenticated/master/reviews/']['parentRoute'],
    FileRoutesByPath['/_authenticated/master/reviews/']['id'],
    FileRoutesByPath['/_authenticated/master/reviews/']['path'],
    FileRoutesByPath['/_authenticated/master/reviews/']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/get-masters/leads/$leadsId' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/get-masters/leads/$leadsId',
    FileRoutesByPath['/_authenticated/(admin)/get-masters/leads/$leadsId']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/get-masters/leads/$leadsId']['id'],
    FileRoutesByPath['/_authenticated/(admin)/get-masters/leads/$leadsId']['path'],
    FileRoutesByPath['/_authenticated/(admin)/get-masters/leads/$leadsId']['fullPath']
  >
}

interface AuthenticatedadminBillingRouteRouteChildren {
  AuthenticatedadminBillingHistoryRoute: typeof AuthenticatedadminBillingHistoryRoute
  AuthenticatedadminBillingStatsRoute: typeof AuthenticatedadminBillingStatsRoute
  AuthenticatedadminBillingTriggerRoute: typeof AuthenticatedadminBillingTriggerRoute
  AuthenticatedadminBillingIndexRoute: typeof AuthenticatedadminBillingIndexRoute
}

const AuthenticatedadminBillingRouteRouteChildren: AuthenticatedadminBillingRouteRouteChildren =
  {
    AuthenticatedadminBillingHistoryRoute:
      AuthenticatedadminBillingHistoryRoute,
    AuthenticatedadminBillingStatsRoute: AuthenticatedadminBillingStatsRoute,
    AuthenticatedadminBillingTriggerRoute:
      AuthenticatedadminBillingTriggerRoute,
    AuthenticatedadminBillingIndexRoute: AuthenticatedadminBillingIndexRoute,
  }

const AuthenticatedadminBillingRouteRouteWithChildren =
  AuthenticatedadminBillingRouteRoute._addFileChildren(
    AuthenticatedadminBillingRouteRouteChildren,
  )

interface AuthenticatedMasterReviewsRouteRouteChildren {
  AuthenticatedMasterReviewsStatsLazyRoute: typeof AuthenticatedMasterReviewsStatsLazyRoute
  AuthenticatedMasterReviewsIndexRoute: typeof AuthenticatedMasterReviewsIndexRoute
}

const AuthenticatedMasterReviewsRouteRouteChildren: AuthenticatedMasterReviewsRouteRouteChildren =
  {
    AuthenticatedMasterReviewsStatsLazyRoute:
      AuthenticatedMasterReviewsStatsLazyRoute,
    AuthenticatedMasterReviewsIndexRoute: AuthenticatedMasterReviewsIndexRoute,
  }

const AuthenticatedMasterReviewsRouteRouteWithChildren =
  AuthenticatedMasterReviewsRouteRoute._addFileChildren(
    AuthenticatedMasterReviewsRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedadminBillingRouteRoute: typeof AuthenticatedadminBillingRouteRouteWithChildren
  AuthenticatedMasterReviewsRouteRoute: typeof AuthenticatedMasterReviewsRouteRouteWithChildren
  AuthenticatedadminCreateCategoryRoute: typeof AuthenticatedadminCreateCategoryRoute
  AuthenticatedadminCreateCityRoute: typeof AuthenticatedadminCreateCityRoute
  AuthenticatedadminRegisterRoute: typeof AuthenticatedadminRegisterRoute
  AuthenticatedMasterJobAssignmentRoute: typeof AuthenticatedMasterJobAssignmentRoute
  AuthenticatedMasterMasterProfileRoute: typeof AuthenticatedMasterMasterProfileRoute
  AuthenticatedMasterNotificationsRoute: typeof AuthenticatedMasterNotificationsRoute
  AuthenticatedMasterSettingsRoute: typeof AuthenticatedMasterSettingsRoute
  AuthenticatedMasterUnlockCityRoute: typeof AuthenticatedMasterUnlockCityRoute
  AuthenticatedMasterUnlockedCitiesRoute: typeof AuthenticatedMasterUnlockedCitiesRoute
  AuthenticatedadminIndexRoute: typeof AuthenticatedadminIndexRoute
  AuthenticatedMasterIndexRoute: typeof AuthenticatedMasterIndexRoute
  AuthenticatedadminCreateJobsIdRoute: typeof AuthenticatedadminCreateJobsIdRoute
  AuthenticatedadminCreateJobsJobsRoute: typeof AuthenticatedadminCreateJobsJobsRoute
  AuthenticatedadminGetMastersIdRoute: typeof AuthenticatedadminGetMastersIdRoute
  AuthenticatedadminGetMastersAllMastersRoute: typeof AuthenticatedadminGetMastersAllMastersRoute
  AuthenticatedMasterLeadsIdRoute: typeof AuthenticatedMasterLeadsIdRoute
  AuthenticatedadminReviewsIndexRoute: typeof AuthenticatedadminReviewsIndexRoute
  AuthenticatedMasterLeadsIndexRoute: typeof AuthenticatedMasterLeadsIndexRoute
  AuthenticatedadminGetMastersLeadsLeadsIdRoute: typeof AuthenticatedadminGetMastersLeadsLeadsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedadminBillingRouteRoute:
    AuthenticatedadminBillingRouteRouteWithChildren,
  AuthenticatedMasterReviewsRouteRoute:
    AuthenticatedMasterReviewsRouteRouteWithChildren,
  AuthenticatedadminCreateCategoryRoute: AuthenticatedadminCreateCategoryRoute,
  AuthenticatedadminCreateCityRoute: AuthenticatedadminCreateCityRoute,
  AuthenticatedadminRegisterRoute: AuthenticatedadminRegisterRoute,
  AuthenticatedMasterJobAssignmentRoute: AuthenticatedMasterJobAssignmentRoute,
  AuthenticatedMasterMasterProfileRoute: AuthenticatedMasterMasterProfileRoute,
  AuthenticatedMasterNotificationsRoute: AuthenticatedMasterNotificationsRoute,
  AuthenticatedMasterSettingsRoute: AuthenticatedMasterSettingsRoute,
  AuthenticatedMasterUnlockCityRoute: AuthenticatedMasterUnlockCityRoute,
  AuthenticatedMasterUnlockedCitiesRoute:
    AuthenticatedMasterUnlockedCitiesRoute,
  AuthenticatedadminIndexRoute: AuthenticatedadminIndexRoute,
  AuthenticatedMasterIndexRoute: AuthenticatedMasterIndexRoute,
  AuthenticatedadminCreateJobsIdRoute: AuthenticatedadminCreateJobsIdRoute,
  AuthenticatedadminCreateJobsJobsRoute: AuthenticatedadminCreateJobsJobsRoute,
  AuthenticatedadminGetMastersIdRoute: AuthenticatedadminGetMastersIdRoute,
  AuthenticatedadminGetMastersAllMastersRoute:
    AuthenticatedadminGetMastersAllMastersRoute,
  AuthenticatedMasterLeadsIdRoute: AuthenticatedMasterLeadsIdRoute,
  AuthenticatedadminReviewsIndexRoute: AuthenticatedadminReviewsIndexRoute,
  AuthenticatedMasterLeadsIndexRoute: AuthenticatedMasterLeadsIndexRoute,
  AuthenticatedadminGetMastersLeadsLeadsIdRoute:
    AuthenticatedadminGetMastersLeadsLeadsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
