/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedadminIndexRouteImport } from './routes/_authenticated/(admin)/index'
import { Route as AuthenticatedmasterUnlockedCitiesRouteImport } from './routes/_authenticated/(master)/unlocked-cities'
import { Route as AuthenticatedmasterUnlockCityRouteImport } from './routes/_authenticated/(master)/unlock-city'
import { Route as AuthenticatedmasterSettingsRouteImport } from './routes/_authenticated/(master)/settings'
import { Route as AuthenticatedmasterMasterProfileRouteImport } from './routes/_authenticated/(master)/master-profile'
import { Route as AuthenticatedmasterMasterRouteImport } from './routes/_authenticated/(master)/master'
import { Route as AuthenticatedmasterJobAssignmentRouteImport } from './routes/_authenticated/(master)/job-assignment'
import { Route as AuthenticatedadminRegisterRouteImport } from './routes/_authenticated/(admin)/register'
import { Route as AuthenticatedadminCreateCityRouteImport } from './routes/_authenticated/(admin)/create-city'
import { Route as AuthenticatedadminCreateCategoryRouteImport } from './routes/_authenticated/(admin)/create-category'
import { Route as AuthenticatedadminCreateJobsJobsRouteImport } from './routes/_authenticated/(admin)/create-jobs/jobs'
import { Route as AuthenticatedadminCreateJobsIdRouteImport } from './routes/_authenticated/(admin)/create-jobs/$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedadminIndexRoute = AuthenticatedadminIndexRouteImport.update({
  id: '/(admin)/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedmasterUnlockedCitiesRoute =
  AuthenticatedmasterUnlockedCitiesRouteImport.update({
    id: '/(master)/unlocked-cities',
    path: '/unlocked-cities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedmasterUnlockCityRoute =
  AuthenticatedmasterUnlockCityRouteImport.update({
    id: '/(master)/unlock-city',
    path: '/unlock-city',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedmasterSettingsRoute =
  AuthenticatedmasterSettingsRouteImport.update({
    id: '/(master)/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedmasterMasterProfileRoute =
  AuthenticatedmasterMasterProfileRouteImport.update({
    id: '/(master)/master-profile',
    path: '/master-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedmasterMasterRoute =
  AuthenticatedmasterMasterRouteImport.update({
    id: '/(master)/master',
    path: '/master',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedmasterJobAssignmentRoute =
  AuthenticatedmasterJobAssignmentRouteImport.update({
    id: '/(master)/job-assignment',
    path: '/job-assignment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminRegisterRoute =
  AuthenticatedadminRegisterRouteImport.update({
    id: '/(admin)/register',
    path: '/register',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminCreateCityRoute =
  AuthenticatedadminCreateCityRouteImport.update({
    id: '/(admin)/create-city',
    path: '/create-city',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminCreateCategoryRoute =
  AuthenticatedadminCreateCategoryRouteImport.update({
    id: '/(admin)/create-category',
    path: '/create-category',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminCreateJobsJobsRoute =
  AuthenticatedadminCreateJobsJobsRouteImport.update({
    id: '/(admin)/create-jobs/jobs',
    path: '/create-jobs/jobs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedadminCreateJobsIdRoute =
  AuthenticatedadminCreateJobsIdRouteImport.update({
    id: '/(admin)/create-jobs/$id',
    path: '/create-jobs/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof authLoginRoute
  '/create-category': typeof AuthenticatedadminCreateCategoryRoute
  '/create-city': typeof AuthenticatedadminCreateCityRoute
  '/register': typeof AuthenticatedadminRegisterRoute
  '/job-assignment': typeof AuthenticatedmasterJobAssignmentRoute
  '/master': typeof AuthenticatedmasterMasterRoute
  '/master-profile': typeof AuthenticatedmasterMasterProfileRoute
  '/settings': typeof AuthenticatedmasterSettingsRoute
  '/unlock-city': typeof AuthenticatedmasterUnlockCityRoute
  '/unlocked-cities': typeof AuthenticatedmasterUnlockedCitiesRoute
  '/': typeof AuthenticatedadminIndexRoute
  '/create-jobs/$id': typeof AuthenticatedadminCreateJobsIdRoute
  '/create-jobs/jobs': typeof AuthenticatedadminCreateJobsJobsRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/create-category': typeof AuthenticatedadminCreateCategoryRoute
  '/create-city': typeof AuthenticatedadminCreateCityRoute
  '/register': typeof AuthenticatedadminRegisterRoute
  '/job-assignment': typeof AuthenticatedmasterJobAssignmentRoute
  '/master': typeof AuthenticatedmasterMasterRoute
  '/master-profile': typeof AuthenticatedmasterMasterProfileRoute
  '/settings': typeof AuthenticatedmasterSettingsRoute
  '/unlock-city': typeof AuthenticatedmasterUnlockCityRoute
  '/unlocked-cities': typeof AuthenticatedmasterUnlockedCitiesRoute
  '/': typeof AuthenticatedadminIndexRoute
  '/create-jobs/$id': typeof AuthenticatedadminCreateJobsIdRoute
  '/create-jobs/jobs': typeof AuthenticatedadminCreateJobsJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/(admin)/create-category': typeof AuthenticatedadminCreateCategoryRoute
  '/_authenticated/(admin)/create-city': typeof AuthenticatedadminCreateCityRoute
  '/_authenticated/(admin)/register': typeof AuthenticatedadminRegisterRoute
  '/_authenticated/(master)/job-assignment': typeof AuthenticatedmasterJobAssignmentRoute
  '/_authenticated/(master)/master': typeof AuthenticatedmasterMasterRoute
  '/_authenticated/(master)/master-profile': typeof AuthenticatedmasterMasterProfileRoute
  '/_authenticated/(master)/settings': typeof AuthenticatedmasterSettingsRoute
  '/_authenticated/(master)/unlock-city': typeof AuthenticatedmasterUnlockCityRoute
  '/_authenticated/(master)/unlocked-cities': typeof AuthenticatedmasterUnlockedCitiesRoute
  '/_authenticated/(admin)/': typeof AuthenticatedadminIndexRoute
  '/_authenticated/(admin)/create-jobs/$id': typeof AuthenticatedadminCreateJobsIdRoute
  '/_authenticated/(admin)/create-jobs/jobs': typeof AuthenticatedadminCreateJobsJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/create-category'
    | '/create-city'
    | '/register'
    | '/job-assignment'
    | '/master'
    | '/master-profile'
    | '/settings'
    | '/unlock-city'
    | '/unlocked-cities'
    | '/'
    | '/create-jobs/$id'
    | '/create-jobs/jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/create-category'
    | '/create-city'
    | '/register'
    | '/job-assignment'
    | '/master'
    | '/master-profile'
    | '/settings'
    | '/unlock-city'
    | '/unlocked-cities'
    | '/'
    | '/create-jobs/$id'
    | '/create-jobs/jobs'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/login'
    | '/_authenticated/(admin)/create-category'
    | '/_authenticated/(admin)/create-city'
    | '/_authenticated/(admin)/register'
    | '/_authenticated/(master)/job-assignment'
    | '/_authenticated/(master)/master'
    | '/_authenticated/(master)/master-profile'
    | '/_authenticated/(master)/settings'
    | '/_authenticated/(master)/unlock-city'
    | '/_authenticated/(master)/unlocked-cities'
    | '/_authenticated/(admin)/'
    | '/_authenticated/(admin)/create-jobs/$id'
    | '/_authenticated/(admin)/create-jobs/jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/(admin)/create-category': {
      id: '/_authenticated/(admin)/create-category'
      path: '/create-category'
      fullPath: '/create-category'
      preLoaderRoute: typeof AuthenticatedadminCreateCategoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/create-city': {
      id: '/_authenticated/(admin)/create-city'
      path: '/create-city'
      fullPath: '/create-city'
      preLoaderRoute: typeof AuthenticatedadminCreateCityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/register': {
      id: '/_authenticated/(admin)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticatedadminRegisterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(master)/job-assignment': {
      id: '/_authenticated/(master)/job-assignment'
      path: '/job-assignment'
      fullPath: '/job-assignment'
      preLoaderRoute: typeof AuthenticatedmasterJobAssignmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(master)/master': {
      id: '/_authenticated/(master)/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedmasterMasterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(master)/master-profile': {
      id: '/_authenticated/(master)/master-profile'
      path: '/master-profile'
      fullPath: '/master-profile'
      preLoaderRoute: typeof AuthenticatedmasterMasterProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(master)/settings': {
      id: '/_authenticated/(master)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedmasterSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(master)/unlock-city': {
      id: '/_authenticated/(master)/unlock-city'
      path: '/unlock-city'
      fullPath: '/unlock-city'
      preLoaderRoute: typeof AuthenticatedmasterUnlockCityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(master)/unlocked-cities': {
      id: '/_authenticated/(master)/unlocked-cities'
      path: '/unlocked-cities'
      fullPath: '/unlocked-cities'
      preLoaderRoute: typeof AuthenticatedmasterUnlockedCitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/': {
      id: '/_authenticated/(admin)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedadminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/create-jobs/$id': {
      id: '/_authenticated/(admin)/create-jobs/$id'
      path: '/create-jobs/$id'
      fullPath: '/create-jobs/$id'
      preLoaderRoute: typeof AuthenticatedadminCreateJobsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(admin)/create-jobs/jobs': {
      id: '/_authenticated/(admin)/create-jobs/jobs'
      path: '/create-jobs/jobs'
      fullPath: '/create-jobs/jobs'
      preLoaderRoute: typeof AuthenticatedadminCreateJobsJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

declare module './routes/_authenticated' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated',
    FileRoutesByPath['/_authenticated']['parentRoute'],
    FileRoutesByPath['/_authenticated']['id'],
    FileRoutesByPath['/_authenticated']['path'],
    FileRoutesByPath['/_authenticated']['fullPath']
  >
}
declare module './routes/(auth)/login' {
  const createFileRoute: CreateFileRoute<
    '/(auth)/login',
    FileRoutesByPath['/(auth)/login']['parentRoute'],
    FileRoutesByPath['/(auth)/login']['id'],
    FileRoutesByPath['/(auth)/login']['path'],
    FileRoutesByPath['/(auth)/login']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/create-category' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/create-category',
    FileRoutesByPath['/_authenticated/(admin)/create-category']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/create-category']['id'],
    FileRoutesByPath['/_authenticated/(admin)/create-category']['path'],
    FileRoutesByPath['/_authenticated/(admin)/create-category']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/create-city' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/create-city',
    FileRoutesByPath['/_authenticated/(admin)/create-city']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/create-city']['id'],
    FileRoutesByPath['/_authenticated/(admin)/create-city']['path'],
    FileRoutesByPath['/_authenticated/(admin)/create-city']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/register' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/register',
    FileRoutesByPath['/_authenticated/(admin)/register']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/register']['id'],
    FileRoutesByPath['/_authenticated/(admin)/register']['path'],
    FileRoutesByPath['/_authenticated/(admin)/register']['fullPath']
  >
}
declare module './routes/_authenticated/(master)/job-assignment' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(master)/job-assignment',
    FileRoutesByPath['/_authenticated/(master)/job-assignment']['parentRoute'],
    FileRoutesByPath['/_authenticated/(master)/job-assignment']['id'],
    FileRoutesByPath['/_authenticated/(master)/job-assignment']['path'],
    FileRoutesByPath['/_authenticated/(master)/job-assignment']['fullPath']
  >
}
declare module './routes/_authenticated/(master)/master' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(master)/master',
    FileRoutesByPath['/_authenticated/(master)/master']['parentRoute'],
    FileRoutesByPath['/_authenticated/(master)/master']['id'],
    FileRoutesByPath['/_authenticated/(master)/master']['path'],
    FileRoutesByPath['/_authenticated/(master)/master']['fullPath']
  >
}
declare module './routes/_authenticated/(master)/master-profile' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(master)/master-profile',
    FileRoutesByPath['/_authenticated/(master)/master-profile']['parentRoute'],
    FileRoutesByPath['/_authenticated/(master)/master-profile']['id'],
    FileRoutesByPath['/_authenticated/(master)/master-profile']['path'],
    FileRoutesByPath['/_authenticated/(master)/master-profile']['fullPath']
  >
}
declare module './routes/_authenticated/(master)/settings' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(master)/settings',
    FileRoutesByPath['/_authenticated/(master)/settings']['parentRoute'],
    FileRoutesByPath['/_authenticated/(master)/settings']['id'],
    FileRoutesByPath['/_authenticated/(master)/settings']['path'],
    FileRoutesByPath['/_authenticated/(master)/settings']['fullPath']
  >
}
declare module './routes/_authenticated/(master)/unlock-city' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(master)/unlock-city',
    FileRoutesByPath['/_authenticated/(master)/unlock-city']['parentRoute'],
    FileRoutesByPath['/_authenticated/(master)/unlock-city']['id'],
    FileRoutesByPath['/_authenticated/(master)/unlock-city']['path'],
    FileRoutesByPath['/_authenticated/(master)/unlock-city']['fullPath']
  >
}
declare module './routes/_authenticated/(master)/unlocked-cities' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(master)/unlocked-cities',
    FileRoutesByPath['/_authenticated/(master)/unlocked-cities']['parentRoute'],
    FileRoutesByPath['/_authenticated/(master)/unlocked-cities']['id'],
    FileRoutesByPath['/_authenticated/(master)/unlocked-cities']['path'],
    FileRoutesByPath['/_authenticated/(master)/unlocked-cities']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/',
    FileRoutesByPath['/_authenticated/(admin)/']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/']['id'],
    FileRoutesByPath['/_authenticated/(admin)/']['path'],
    FileRoutesByPath['/_authenticated/(admin)/']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/create-jobs/$id' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/create-jobs/$id',
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/$id']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/$id']['id'],
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/$id']['path'],
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/$id']['fullPath']
  >
}
declare module './routes/_authenticated/(admin)/create-jobs/jobs' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/(admin)/create-jobs/jobs',
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/jobs']['parentRoute'],
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/jobs']['id'],
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/jobs']['path'],
    FileRoutesByPath['/_authenticated/(admin)/create-jobs/jobs']['fullPath']
  >
}

interface AuthenticatedRouteChildren {
  AuthenticatedadminCreateCategoryRoute: typeof AuthenticatedadminCreateCategoryRoute
  AuthenticatedadminCreateCityRoute: typeof AuthenticatedadminCreateCityRoute
  AuthenticatedadminRegisterRoute: typeof AuthenticatedadminRegisterRoute
  AuthenticatedmasterJobAssignmentRoute: typeof AuthenticatedmasterJobAssignmentRoute
  AuthenticatedmasterMasterRoute: typeof AuthenticatedmasterMasterRoute
  AuthenticatedmasterMasterProfileRoute: typeof AuthenticatedmasterMasterProfileRoute
  AuthenticatedmasterSettingsRoute: typeof AuthenticatedmasterSettingsRoute
  AuthenticatedmasterUnlockCityRoute: typeof AuthenticatedmasterUnlockCityRoute
  AuthenticatedmasterUnlockedCitiesRoute: typeof AuthenticatedmasterUnlockedCitiesRoute
  AuthenticatedadminIndexRoute: typeof AuthenticatedadminIndexRoute
  AuthenticatedadminCreateJobsIdRoute: typeof AuthenticatedadminCreateJobsIdRoute
  AuthenticatedadminCreateJobsJobsRoute: typeof AuthenticatedadminCreateJobsJobsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedadminCreateCategoryRoute: AuthenticatedadminCreateCategoryRoute,
  AuthenticatedadminCreateCityRoute: AuthenticatedadminCreateCityRoute,
  AuthenticatedadminRegisterRoute: AuthenticatedadminRegisterRoute,
  AuthenticatedmasterJobAssignmentRoute: AuthenticatedmasterJobAssignmentRoute,
  AuthenticatedmasterMasterRoute: AuthenticatedmasterMasterRoute,
  AuthenticatedmasterMasterProfileRoute: AuthenticatedmasterMasterProfileRoute,
  AuthenticatedmasterSettingsRoute: AuthenticatedmasterSettingsRoute,
  AuthenticatedmasterUnlockCityRoute: AuthenticatedmasterUnlockCityRoute,
  AuthenticatedmasterUnlockedCitiesRoute:
    AuthenticatedmasterUnlockedCitiesRoute,
  AuthenticatedadminIndexRoute: AuthenticatedadminIndexRoute,
  AuthenticatedadminCreateJobsIdRoute: AuthenticatedadminCreateJobsIdRoute,
  AuthenticatedadminCreateJobsJobsRoute: AuthenticatedadminCreateJobsJobsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
